import { StyleSheet } from 'react-native';

export const createStoreStyles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  headerTitle: { fontSize: 18, fontWeight: '600' },
  scrollContent: { paddingHorizontal: 24 },
  logoSection: { alignItems: 'center', marginBottom: 24 },
  logoPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
  },
  logoPlaceholderText: { fontSize: 12, color: '#9CA3AF', marginTop: 6 },
  logoImage: { width: 120, height: 120, borderRadius: 60 },
  formSection: { gap: 16 },
  fieldLabel: { fontSize: 14, fontWeight: '500', color: '#101828', marginBottom: 8 },
  subscriptionCard: {
    backgroundColor: '#FFFBEB',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  subscriptionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  subscriptionTitle: { fontSize: 16, fontWeight: '600', color: '#92400E' },
  subscriptionDescription: { fontSize: 14, color: '#92400E', lineHeight: 22 },
  boldText: { fontWeight: '700' },
  subscriptionFeatures: { marginTop: 12, gap: 8 },
  featureRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  featureText: { fontSize: 13, color: '#92400E' },
  createButton: {
    backgroundColor: '#155DFC',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 8,
  },
  createButtonDisabled: { opacity: 0.7 },
  createButtonText: { color: '#FFF', fontSize: 16, fontWeight: '600' },
});
