import { StyleSheet } from 'react-native';

export const createProductStyles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  headerTitle: { fontSize: 18, fontWeight: '600' },
  scrollContent: { paddingHorizontal: 24 },
  section: { marginBottom: 28 },
  sectionTitle: { fontSize: 18, fontWeight: '600', color: '#101828', marginBottom: 4 },
  sectionSubtitle: { fontSize: 13, color: '#6B7280', marginBottom: 14 },
  formGroup: { gap: 16 },
  fieldLabel: { fontSize: 14, fontWeight: '500', color: '#101828', marginBottom: 8 },
  imagesGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  imageContainer: { width: 90, height: 90, borderRadius: 12, overflow: 'hidden' },
  imageThumb: { width: '100%', height: '100%' },
  removeImageBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  coverBadge: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(21,93,252,0.8)',
    paddingVertical: 2,
    alignItems: 'center',
  },
  coverBadgeText: { fontSize: 10, color: '#FFF', fontWeight: '600' },
  addImageBtn: {
    width: 90,
    height: 90,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9FAFB',
  },
  deliveryOptions: { flexDirection: 'row', gap: 12 },
  deliveryOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  deliveryOptionActive: { borderColor: '#155DFC', backgroundColor: '#EEF2FF' },
  deliveryOptionText: { fontSize: 14, fontWeight: '500', color: '#6B7280' },
  deliveryOptionTextActive: { color: '#155DFC' },
  submitButton: {
    backgroundColor: '#155DFC',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
  },
  submitButtonDisabled: { opacity: 0.7 },
  submitButtonText: { color: '#FFF', fontSize: 16, fontWeight: '600' },
});
