import { StyleSheet } from 'react-native';

export const createRestaurantStyles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  headerTitle: { fontSize: 18, fontWeight: '600' },
  scrollContent: { paddingHorizontal: 24 },
  progressContainer: { paddingHorizontal: 24, marginBottom: 16 },
  progressTrack: {
    height: 6,
    backgroundColor: '#E5E7EB',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 6,
  },
  progressFill: { height: '100%', backgroundColor: '#155DFC', borderRadius: 3 },
  progressText: { fontSize: 12, color: '#6B7280' },
  screenContent: { gap: 16 },
  screenTitle: { fontSize: 22, fontWeight: '700', color: '#101828' },
  screenSubtitle: { fontSize: 14, color: '#6B7280', marginBottom: 8 },
  fieldLabel: { fontSize: 14, fontWeight: '500', color: '#101828', marginBottom: 8 },
  imagePicker: {
    height: 160,
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    overflow: 'hidden',
  },
  imagePickerText: { fontSize: 13, color: '#9CA3AF', marginTop: 8 },
  pickedImage: { width: '100%', height: '100%' },
  deliveryRadiusInfo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#EEF2FF',
    padding: 14,
    borderRadius: 12,
    gap: 10,
  },
  deliveryRadiusText: { flex: 1, fontSize: 13, color: '#3730A3', lineHeight: 18 },
  bottomActions: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingVertical: 14,
    paddingBottom: 34,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  backButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  backButtonText: { fontSize: 16, fontWeight: '600', color: '#101828' },
  nextButton: {
    flex: 2,
    backgroundColor: '#155DFC',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
  },
  nextButtonDisabled: { opacity: 0.7 },
  nextButtonText: { color: '#FFF', fontSize: 16, fontWeight: '600' },
});
