import { StyleSheet } from 'react-native';

export const orderConfirmedStyles = StyleSheet.create({
  container: { flex: 1 },
  content: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32 },
  iconCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#10B981',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  title: { fontSize: 26, fontWeight: '700', marginBottom: 8 },
  subtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 32,
  },
  card: {
    width: '100%',
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 16,
  },
  cardRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8 },
  cardLabel: { fontSize: 14, color: '#6B7280' },
  cardValue: { fontSize: 14, fontWeight: '600', color: '#101828' },
  priceText: { color: '#155DFC' },
  divider: { height: 1, backgroundColor: '#F3F4F6' },
  itemsSummary: {
    width: '100%',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
  },
  itemsSummaryTitle: { fontSize: 14, fontWeight: '600', color: '#101828', marginBottom: 8 },
  itemText: { fontSize: 13, color: '#6B7280', marginBottom: 4 },
  bottomActions: { paddingHorizontal: 24, paddingBottom: 34, gap: 12 },
  trackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#155DFC',
    paddingVertical: 16,
    borderRadius: 14,
  },
  trackButtonText: { color: '#FFF', fontSize: 16, fontWeight: '600' },
  homeButton: {
    alignItems: 'center',
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  homeButtonText: { fontSize: 16, fontWeight: '600', color: '#101828' },
});
