import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const productDetailStyles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  headerBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerRight: { flexDirection: 'row', gap: 8 },
  imagePlaceholder: {
    width: width,
    height: width * 0.75,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePlaceholderText: { fontSize: 14, color: '#9CA3AF', marginTop: 8 },
  discountBadge: {
    position: 'absolute',
    top: 16,
    left: 16,
    backgroundColor: '#EF4444',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  discountText: { color: '#FFF', fontSize: 12, fontWeight: '700' },
  content: { padding: 24 },
  tagsRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  tagChip: {
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  tagText: { fontSize: 12, color: '#155DFC', fontWeight: '500' },
  productName: { fontSize: 22, fontWeight: '700', marginBottom: 8 },
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  price: { fontSize: 24, fontWeight: '700', color: '#155DFC' },
  originalPrice: {
    fontSize: 16,
    color: '#9CA3AF',
    textDecorationLine: 'line-through',
  },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 20 },
  ratingText: { fontSize: 14, color: '#6B7280' },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 16, fontWeight: '600', color: '#101828', marginBottom: 10 },
  description: { fontSize: 14, color: '#6B7280', lineHeight: 22 },
  deliveryOptions: { flexDirection: 'row', gap: 10 },
  deliveryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  deliveryChipText: { fontSize: 13, color: '#155DFC', fontWeight: '500' },
  sellerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    padding: 14,
    borderRadius: 14,
  },
  sellerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sellerInfo: { flex: 1, marginLeft: 12 },
  sellerNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  sellerName: { fontSize: 15, fontWeight: '600', color: '#101828' },
  sellerDetail: { fontSize: 13, color: '#6B7280', marginTop: 2 },
  sellerRating: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  sellerRatingText: { fontSize: 13, fontWeight: '500', color: '#101828' },
  visitStoreBtn: {
    borderWidth: 1,
    borderColor: '#155DFC',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  visitStoreText: { fontSize: 13, color: '#155DFC', fontWeight: '600' },
  verifiedBadge: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  verifiedText: { fontSize: 12, color: '#155DFC', fontWeight: '500' },
  securityContainer: {
    backgroundColor: '#ECFDF5',
    padding: 16,
    borderRadius: 14,
    marginBottom: 16,
  },
  securityHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  securityTitle: { fontSize: 15, fontWeight: '600', color: '#065F46' },
  securityItems: { gap: 8 },
  securityItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  securityItemText: { fontSize: 13, color: '#065F46' },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 34,
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 5,
  },
  chatSellerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#155DFC',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
  },
  chatSellerText: { fontSize: 14, color: '#155DFC', fontWeight: '600' },
  addToCartBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#155DFC',
    paddingVertical: 12,
    borderRadius: 12,
  },
  addToCartText: { fontSize: 14, color: '#FFF', fontWeight: '600' },
  buyNowBtn: {
    backgroundColor: '#101828',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  buyNowText: { fontSize: 14, color: '#FFF', fontWeight: '600' },
});
