import { StyleSheet } from 'react-native';

export const trackOrderStyles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  headerTitle: { fontSize: 18, fontWeight: '600' },
  scrollContent: { paddingHorizontal: 24 },
  orderInfoCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 18,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  orderInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  orderInfoLabel: { fontSize: 14, color: '#6B7280' },
  orderInfoValue: { fontSize: 14, fontWeight: '600', color: '#101828' },
  mapPlaceholder: {
    height: 180,
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  mapPlaceholderText: { fontSize: 14, color: '#9CA3AF', marginTop: 8 },
  section: { marginBottom: 24 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#101828',
    marginBottom: 16,
  },
  stepsContainer: {},
  stepRow: { flexDirection: 'row', minHeight: 72 },
  stepIndicatorCol: { alignItems: 'center', width: 32 },
  stepDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotCompleted: { backgroundColor: '#10B981', borderColor: '#10B981' },
  stepDotCurrent: { borderColor: '#155DFC', borderWidth: 3 },
  stepDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#155DFC',
  },
  stepLine: {
    flex: 1,
    width: 2,
    backgroundColor: '#E5E7EB',
    marginVertical: 4,
  },
  stepLineCompleted: { backgroundColor: '#10B981' },
  stepContent: { flex: 1, marginLeft: 14, paddingBottom: 24 },
  stepTitle: { fontSize: 15, fontWeight: '500', color: '#9CA3AF' },
  stepTitleActive: { color: '#101828', fontWeight: '600' },
  stepDescription: { fontSize: 13, color: '#9CA3AF', marginTop: 2 },
  stepTime: { fontSize: 12, color: '#155DFC', fontWeight: '500', marginTop: 4 },
  deliveryPersonCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    padding: 16,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  deliveryAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deliveryInfo: { flex: 1, marginLeft: 12 },
  deliveryName: { fontSize: 15, fontWeight: '600', color: '#101828' },
  deliveryRating: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  deliveryRatingText: { fontSize: 13, color: '#6B7280' },
  callBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#155DFC',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  messageBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#155DFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
