export const CATEGORIES = [
  { id: 1, emoji: '🍽️', label: 'All', isActive: true },
  { id: 2, emoji: '🍲', label: 'African', isActive: false },
  { id: 3, emoji: '🍔', label: 'Fast Food', isActive: false },
  { id: 4, emoji: '🍜', label: 'Chinese', isActive: false },
  { id: 5, emoji: '🥤', label: 'Drinks', isActive: false },
  { id: 6, emoji: '🍰', label: 'Desserts', isActive: false },
];

export const FEATURED_RESTAURANTS = [
  {
    id: 1,
    name: "Mama's Kitchen",
    cuisine: 'African Cuisine',
    rating: 4.8,
    deliveryTime: '25-35 min',
    fee: 'GHC 8 fee',
    image: 'https://dummyimage.com/280x180/000/fff.png',
    isOpen: true,
    isNightShop: true,
  },
  {
    id: 2,
    name: 'Burger Hub',
    cuisine: 'American Fast Food',
    rating: 4.6,
    deliveryTime: '20-30 min',
    fee: 'GHC 10 fee',
    image: 'https://dummyimage.com/280x180/000/fff.png',
    isOpen: true,
    isNightShop: true,
  },
  {
    id: 3,
    name: 'Sweet Treats',
    cuisine: 'Desserts & Beverages',
    rating: 4.9,
    deliveryTime: '15-25 min',
    fee: 'GHC 5 fee',
    image: 'https://dummyimage.com/280x180/000/fff.png',
    isOpen: true,
    isNightShop: true,
  },
];

export const ALL_RESTAURANTS = [
  {
    id: 1,
    name: "Mama's Kitchen",
    cuisine: 'African Cuisine',
    rating: 4.8,
    reviewCount: 342,
    deliveryTime: '25-35 min',
    fee: 'GHC 8',
    image: 'https://dummyimage.com/96x96/000/fff.png',
    isOpen: true,
    tags: ['Fast Delivery', 'Popular', '🌙 Night'],
    category: 'African',
  },
  {
    id: 2,
    name: 'Burger Hub',
    cuisine: 'American Fast Food',
    rating: 4.6,
    reviewCount: 218,
    deliveryTime: '20-30 min',
    fee: 'GHC 10',
    image: 'https://dummyimage.com/96x96/000/fff.png',
    isOpen: true,
    tags: ['Fast Service', 'Student Discount', '🌙 Night'],
    category: 'Fast Food',
  },
  {
    id: 3,
    name: 'Oriental Express',
    cuisine: 'Chinese & Asian',
    rating: 4.7,
    reviewCount: 156,
    deliveryTime: '30-40 min',
    fee: 'GHC 12',
    image: 'https://dummyimage.com/96x96/000/fff.png',
    isOpen: true,
    tags: ['Vegetarian Options', 'Halal'],
    category: 'Chinese',
  },
  {
    id: 4,
    name: 'Sweet Treats',
    cuisine: 'Desserts & Beverages',
    rating: 4.9,
    reviewCount: 289,
    deliveryTime: '15-25 min',
    fee: 'GHC 5',
    image: 'https://dummyimage.com/96x96/000/fff.png',
    isOpen: true,
    tags: ['Fresh Daily', 'Custom Orders', '🌙 Night'],
    category: 'Desserts',
  },
  {
    id: 5,
    name: 'Spice Kingdom',
    cuisine: 'African Cuisine',
    rating: 4.5,
    reviewCount: 194,
    deliveryTime: '30-40 min',
    fee: 'GHC 8',
    image: 'https://dummyimage.com/96x96/000/fff.png',
    isOpen: true,
    tags: ['Spicy', 'Fresh'],
    category: 'African',
  },
];

export default { CATEGORIES, FEATURED_RESTAURANTS, ALL_RESTAURANTS };
