import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: { flex: 1 },
  content: { flex: 1 },
  servicesContainer: {
    flexDirection: 'row',
    gap: 16,
    marginHorizontal: 16,
    marginTop: 16,
  },
  serviceCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 15,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    overflow: 'hidden',
  },
  serviceIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  serviceText: { flexDirection: 'column', flex: 1 },
  serviceTitle: { fontSize: 16, fontWeight: '400', color: '#101828', marginBottom: 4 },
  serviceSubtitle: { fontSize: 12, color: '#6B7280' },
  categoriesContainer: { marginTop: 16, paddingHorizontal: 16 },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 18, fontWeight: '700' },
  seeAll: { fontSize: 14, color: '#155DFC', fontWeight: '500' },
  productsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 12,
    gap: 12,
  },
  productCard: {
    width: '47%',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  productImage: { width: '100%', height: 180 },
  productBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: '#155DFC',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeText: { color: '#fff', fontSize: 11, fontWeight: '600' },
  productInfo: { padding: 10 },
  productTitle: { fontSize: 14, fontWeight: '500', color: '#101828' },
  productPrice: { fontSize: 16, fontWeight: '700', color: '#155DFC', marginTop: 4 },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  ratingText: { fontSize: 12, color: '#6B7280' },
  recentCard: {
    width: 140,
    marginLeft: 16,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  recentImage: { width: '100%', height: 140 },
  recentTitle: { fontSize: 13, fontWeight: '500', color: '#101828', marginHorizontal: 8, marginTop: 6 },
  recentPrice: { fontSize: 14, fontWeight: '700', color: '#155DFC', marginHorizontal: 8, marginBottom: 8 },
});
